### ISSUE TITLE
CoSim client implemented as a Container

### ISSUE THREAD

**Issue by timrulebosch** [dspace-group/veos-cosim-client#18]
Do you have refence doc or examples for a CoSim client implemented as a Docker container? The docker container, containing a CoSim client, would then connect to the CoSim server via TCP and operate as normal.

**Comment by ACanisLupus** [comment]
@timrulebosch We have no immediate plans to provide a docker container, since it would be trivial. The CoSim client only connects via TCP to a CoSim server running inside of dSPACE VEOS.
We do however provide a reference doc and examples for running dSPACE VEOS in docker containers. Currently, we support Windows and Linux dockers. Please refer to the official dSPACE VEOS documentation.
